-- INSERT INTO items (product, price) VALUES ('small-desk',100),('large-desk',300),('fan',80);
-- INSERT INTO customers (first_name, last_name) VALUES ('Greg','Jones'),
-- ('Sandra','Jones'),('Scott','Scott'),('Trevor','Green'),('Melanie','Johnson');
-- SELECT * FROM public.items;
-- SELECT * FROM items WHERE price > 80;
-- SELECT * FROM items WHERE price < 400 ;
-- SELECT * FROM customers WHERE last_name = 'Smith';
-- SELECT * FROM customers WHERE last_name = 'Jones';
-- SELECT * FROM customers WHERE first_name != 'Jones';
